version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_NAME=thesisProposal
      - DB_PASS=password

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=thesisProposal

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    depends_on:
      - app